apiVersion: apps/v1
kind: Deployment
metadata:
  name: prefect-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prefect-server
  template:
    metadata:
      labels:
        app: prefect-server
    spec:
      containers:
        - name: prefect-server
          image: prefect-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 4200
          env:
            - name: PREFECT_SERVER__TELEMETRY__ENABLED
              value: "false"
            - name: PREFECT_UI_URL
              value: "http://localhost:4200/api"
            - name: PREFECT_API_URL
              value: "http://localhost:4200/api"
            - name: PREFECT_SERVER_API_HOST
              value: "0.0.0.0"