apiVersion: apps/v1
kind: Deployment
metadata:
  name: prefect-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prefect-worker
  template:
    metadata:
      labels:
        app: prefect-worker
    spec:
      containers:
        - name: prefect-worker
          image: prefect-worker:latest
          imagePullPolicy: Never
          env:
            - name: PREFECT__BACKEND
              value: "server"
            - name: PREFECT_API_URL
              value: "http://prefect-service:4200/api"